config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, :only => [:show] do
    get :search, on: :collection
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :posts, :only => [:show, :new, :create, :edit, :update, :destroy] do
    get :search, on: :collection
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end

  resources :care_recipients, :only => [:index, :show, :new, :create, :edit, :update] do
    get :search, on: :collection
  end

  resources :comments, :only => [:new, :create, :destroy]
  resources :tops, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:index, :new, :create, :show]
  resources :care_diaries, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :care_recipients, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/care_diary.rb
class CareDiary < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { in: 1..10 }
  validates :date, presence: true
  validates :temperature, presence: true
  validates :breakfast_meal_intake, presence: true, numericality: { only_integer: true, less_than:11}
  validates :lunch_meal_intake, presence: true, numericality: { only_integer: true, less_than:11}
  validates :dinner_meal_intake, presence: true, numericality: { only_integer: true, less_than:11}
  validates :notes, presence: true,  length: { in: 1..255 }
  validates :user_id, presence: true
end

app/controllers/care_diaries_controller.rb
class CareDiariesController < ApplicationController
  before_action :authenticate_user!
  before_action :user_role?

  def index
    cd_date = params[:cd_date]
    if cd_date.present?
      @cd_date = cd_date.to_date
      @care_diaries = current_user.care_diaries.where(date: @cd_date.beginning_of_month..@cd_date.end_of_month).order(date: "ASC")
    else
      @care_diary = current_user.care_diaries.order(date: :desc).first
      if @care_diary.present?
        @cd_date = @care_diary.date
        @care_diaries = current_user.care_diaries.where(date: @cd_date.beginning_of_month..@cd_date.end_of_month).order(date: "ASC")
      end
    end
  end

  def show
    @care_diary = CareDiary.find(params[:id])
  end

  def new
    @date = Date.today
    @care_diary = CareDiary.new
  end

  def create
    @care_diary = CareDiary.new(care_diary_params)
    if @care_diary.save
      redirect_to "/care_diaries"
    else
      redirect_to "/care_diaries/new"
    end
  end

  def edit
    @care_diary = CareDiary.find(params[:id])
  end

  def update
    @care_diary = CareDiary.find(params[:id])
    @care_diary.update(care_diary_params)
    redirect_to "/care_diaries/#{params[:id]}"
  end

  def destroy
    care_diary = CareDiary.find(params[:id])
    care_diary.destroy
    redirect_to care_diaries_path

  end

  private
  def user_role?
    if current_user.role != 1
      redirect_to "/"
    end
  end


  def care_diary_params
    params.require(:care_diary).permit(:notes, :temperature, :date, :breakfast_meal_intake, :lunch_meal_intake, :dinner_meal_intake, :user_id, :name)
  end
end

app/helpers/care_diarys_helper.rb
module CareDiarysHelper
end

app/views/care_diaries/edit.html.erb
<div class="care-diary-block container">
  <%= form_for @care_diary do |f| %>
    <%= f.label :date, "日付" %>
    <%= f.date_field :date, value:@date, class: "care-diary-date-form" %>
    <%= f.label :temperature, "体温" %>
    <div class="care-diary-form-block">
      <%= f.number_field :temperature, step: "0.1" %>
      <p>℃</p>
    </div>
    <div>
      <%= f.label :breakfast_meal_intake, "朝食量" %>
      <div class="care-diary-form-block">
        <%= f.number_field :breakfast_meal_intake %>
        <p>割</p>
      </div>
      <%= f.label :lunch_meal_intake, "昼食量" %>
      <div class="care-diary-form-block">
        <%= f.number_field :lunch_meal_intake %>
        <p>割</p>
      </div>
      <%= f.label :dinner_meal_intake, "夕食量" %>
      <div class="care-diary-form-block">
        <%= f.number_field :dinner_meal_intake %>
        <p>割</p>
      </div>
    </div>
    <%= f.text_area :notes, class: "care-diary-notes-form" %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :name, :value => current_user.name %>
    <%= f.submit "編集する", class: "care-diary-btn" %>
  <% end %>
</div>

app/views/care_diaries/index.html.erb
<div class="page-title">
  <p><%= current_user.name %>の介護記録</p>
</div>
<div class="care-diary-edit">
  <p class="care-diary-btn"><%= link_to "介護日誌作成", new_care_diary_path %></p>
</div>
<% if @care_diaries.present? %>
  <div class="care-diary-date">
    <p><%= @cd_date.year %>年</p>
    <p><%= @cd_date.month %>月</p>
  </div>
  <%= link_to care_diaries_path(cd_date: @cd_date.last_month) do %>
    <i class="fas fa-caret-left left-button"></i>
  <% end %>
  <%= link_to care_diaries_path(cd_date: @cd_date.next_month) do %>
    <i class="fas fa-caret-right right-button"></i>
  <% end %>
  <div class="care-diary-block1">
    <% @care_diaries.each do |c| %>
      <div class="care-diary-index-block2">
        <%= link_to care_diary_path(c.id) do %>
          <div>
            <p class="date"><%= c.date.day %>日</p>
            <p>体温<%= c.temperature %>℃</p>
          </div>
          <div>
            <p>食事量</p>
            <p>朝<%= c.breakfast_meal_intake %>割</p>
            <p>昼<%= c.lunch_meal_intake %>割</p>
            <p>夜<%= c.dinner_meal_intake %>割</p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/care_diaries/new.html.erb
<div class="care-diary-block container">
  <%= form_for @care_diary do |f| %>
    <%= f.label :date, "日付" %>
    <%= f.date_field :date, value:@date, class: "care-diary-date-form" %>
    <%= f.label :temperature, "体温" %>
    <div class="care-diary-form-block">
      <%= f.number_field :temperature, step: "0.1" %>
      <p>℃</p>
    </div>
    <div>
      <%= f.label :breakfast_meal_intake, "朝食量" %>
      <div class="care-diary-form-block">
        <%= f.number_field :breakfast_meal_intake %>
        <p>割</p>
      </div>
      <%= f.label :lunch_meal_intake, "昼食量" %>
      <div class="care-diary-form-block">
        <%= f.number_field :lunch_meal_intake %>
        <p>割</p>
      </div>
      <%= f.label :dinner_meal_intake, "夕食量" %>
      <div class="care-diary-form-block">
        <%= f.number_field :dinner_meal_intake %>
        <p>割</p>
      </div>
    </div>
    <%= f.text_area :notes, class: "care-diary-notes-form" %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :name, :value => current_user.name %>
    <%= f.submit "作成する", class: "care-diary-btn" %>
  <% end %>
</div>

app/views/care_diaries/show.html.erb
<div class="page-title">
  <p><%= @care_diary.name %>の介護記録</p>
</div>
<div class="care-diary-date">
  <p><%= @care_diary.date.year %>年</p>
  <p><%= @care_diary.date.month %>月</p>
</div>
<div class="care-diary-contents">
  <%= link_to "/@care_diarys/#{@care_diary.id}", method: :delete, data: {confirm: "削除しますか？"}  do %>
    <i class="fas fa-trash-alt"></i>
  <% end %>
  <%= link_to edit_care_diary_path(@care_diary), class: "care-diary-edit-btn" do %>
    <i class="fas fa-edit"></i>
  <% end %>
</div>
<div class="care-diary-block-show">
  <div class="block1">
    <p class="date"><%= @care_diary.date.day %>日</p>
    <p class="temperature">体温：<%= @care_diary.temperature %>℃</p>
  </div>
  <div class="block2">
    <p>食事量</p>
    <p class="breakfast-meal-intake"><%= @care_diary.breakfast_meal_intake %>割</p>
    <p class="lunch-meal-intake"><%= @care_diary.lunch_meal_intake %>割</p>
    <p class="dinner-meal-intake"><%= @care_diary.dinner_meal_intake %>割</p>
  </div>
  <p class="notes">特記事項：<br><%= @care_diary.notes %></p>
</div>