config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, :only => [:show] do
    get :search, on: :collection
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :posts, :only => [:show, :new, :create, :edit, :update, :destroy] do
    get :search, on: :collection
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end

  resources :care_recipients, :only => [:index, :show, :new, :create, :edit, :update] do
    get :search, on: :collection
  end

  resources :comments, :only => [:new, :create, :destroy]
  resources :tops, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:index, :new, :create, :show]
  resources :care_diaries, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :care_recipients, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/care_recipient.rb
class CareRecipient < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { in: 1..10 }
  validates :sex, presence: true
  validates :birthday, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
  validates :facility_in_charge, length: { in: 1..50 }, allow_blank: true
  validates :manager_in_charge, length: { in: 1..10 }, allow_blank: true
  validates :degree_care_required, presence: true, numericality: { only_integer: true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5 }
  validates :dementia, presence: true
  validates :notes, length: { in: 1..255 }

  enum sex: { 男: 1, 女: 2 }
  enum dementia: { 有り: 1, 無し: 2 }


end

app/controllers/care_recipients_controller.rb
class CareRecipientsController < ApplicationController
  before_action :authenticate_user!
  before_action :user_role?

  def index
    @care_recipients = current_user.care_recipients.all

  end

  def new
    @care_recipient = CareRecipient.new
  end

  def create
    if CareRecipient.create(params_int(care_recipient_params))
      redirect_to "/care_recipients"
    else
      redirect_to "/care_recipient/new"
    end
  end

  def show
    @care_recipient = CareRecipient.find(params[:id])
  end

  def edit
    @care_recipient = CareRecipient.find(params[:id])
  end

  def update
    @care_recipient = CareRecipient.find(params[:id])
    if @care_recipient.update(params_int(care_recipient_params))
      redirect_to "/care_recipients/#{params[:id]}"
    else
      redirect_to "/care_recipients/#{params[:id]}/edit"
    end
  end

  def destroy
    care_recipient = CareRecipient.find(params[:id])
    care_recipient.destroy
  end

  def search
    if params[:name].present?
      @care_recipients = CareRecipient.where('name LIKE ?', "%#{params[:name]}%")
    else
      @care_recipients = CareRecipient.none
    end
  end

  private
  def user_role?
    if current_user.role == 1
      redirect_to "/"
    end
  end


  def care_recipient_params
    params.require(:care_recipient).permit(
      :name,
      :sex,
      :birthday,
      :age,
      :degree_care_required,
      :facility_in_charge,
      :manager_in_charge,
      :dementia,
      :notes,
      :user_id
    )
  end

  def params_int(care_recipient_params)
    care_recipient_params.each do |key,value|
      if integer_string?(value)
        care_recipient_params[key]=value.to_i
      end
    end
  end
end

app/helpers/care_recipients_helper.rb
module CareRecipientsHelper
end

app/views/care_recipients/_care_recipients.html.erb
<table class="care-recipient-tbl">
  <tr><th></th><th>名前</th><th class="sex">性別</th><th>事業所</th><th>ケアマネ</th><th>要介護度</th></tr>
  <% @care_recipients.each.with_index(1) do |cr,i| %>
    <tr>
      <th><%= link_to "#{i}", care_recipient_path(cr.id),class: "white" %></th>
      <td><%= link_to "#{cr.name}", care_recipient_path(cr.id) %></td>
      <td><%= link_to "#{cr.sex}", care_recipient_path(cr.id) %></td>
      <td><%= link_to "#{cr.facility_in_charge}", care_recipient_path(cr.id) %></td>
      <td><%= link_to "#{cr.manager_in_charge}", care_recipient_path(cr.id) %></td>
      <td><%= link_to "#{cr.degree_care_required}", care_recipient_path(cr.id) %></td>
    </tr>
  <% end %>
</table>

app/views/care_recipients/edit.html.erb
<div class="care-recipient-block1 container">
  <%= form_for @care_recipient do |f| %>
    <div class="care-recipient-block2">
      <%= f.label :name, "名前", class: "care-recipient-label" %>
      <%= f.text_field :name, class: "name" %>
      <%= f.label :sex, "性別", class: "care-recipient-label" %>
      <%= f.select :sex, CareRecipient.sexes.keys, {}, class: "sex" %>
    </div>
    <div class="care-recipient-block2">
      <%= f.label :age, "年齢", class: "care-recipient-label" %>
      <%= f.number_field :age, class: "age" %>
      <%= f.label :birthday, "誕生日", class: "care-recipient-label" %>
      <%= f.date_field :birthday %>
    </div>
    <% if current_user.role == 2 %>
      <div class="care-recipient-block3">
        <%= f.label :facility_in_charge, "担当事業所", class: "care-recipient-label" %>
        <%= f.text_field :facility_in_charge, class: "facility_in_charge" %>
        <%= f.label :manager_in_charge, "担当ケアマネージャー", class: "care-recipient-label" %>
        <%= f.text_field :manager_in_charge, class: "manager_in_charge" %>
      </div>
    <% end %>
    <div class="care-recipient-block2">
      <%= f.label :degree_care_required, "要介護度", class: "care-recipient-label" %>
      <%= f.select :degree_care_required, [[1],[2],[3],[4],[5]], {}, class: "degree-care-required" %>
      <%= f.label :dementia, "認知症", class: "care-recipient-label" %>
      <%= f.select :dementia, [["有り", 1],["無し", 2]], {}, class: "dementia" %>
    </div>
    <div class="care-recipient-block2">
      <%= f.label :notes, "特記事項", class: "care-recipient-label" %>
      <%= f.text_area :notes, class: "notes" %>
    </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "編集する", class: "care-diary-btn" %>
  <% end %>
</div>

app/views/care_recipients/index.html.erb
<div class="page-title">
  <p>利用者一覧</p>
</div>
<div class="care-recipient-search">
  <%= form_with url: search_care_recipients_path, method: :get, local: true do |f| %>
    <%= f.text_field :name, class: "form" %>
    <%= f.submit "検索する", class: "btn" %>
  <% end %>
</div>
<div class="care-recipient-btn">
  <%= link_to "利用者を作成する", new_care_recipient_path %>
</div>
<%= render 'care_recipients/care_recipients' %>

app/views/care_recipients/new.html.erb
<div class="care-recipient-block1 container">
  <%= form_for @care_recipient do |f| %>
    <div class="care-recipient-block2">
      <%= f.label :name, "名前", class: "care-recipient-label" %>
      <%= f.text_field :name, class: "name" %>
      <%= f.label :sex, "性別", class: "care-recipient-label" %>
      <%= f.select :sex, CareRecipient.sexes.keys, {}, class: "sex" %>
    </div>
    <div class="care-recipient-block2">
      <%= f.label :age, "年齢", class: "care-recipient-label" %>
      <%= f.number_field :age, class: "age" %>
      <%= f.label :birthday, "誕生日", class: "care-recipient-label" %>
      <%= f.date_field :birthday %>
    </div>
    <% if current_user == 2 %>
      <div class="care-recipient-block3">
        <%= f.label :facility_in_charge, "担当事業所", class: "care-recipient-label" %>
        <%= f.text_field :facility_in_charge, class: "facility_in_charge" %>
        <%= f.label :manager_in_charge, "担当ケアマネージャー", class: "care-recipient-label" %>
        <%= f.text_field :manager_in_charge, class: "manager_in_charge" %>
      </div>
    <% end %>
    <div class="care-recipient-block2">
      <%= f.label :degree_care_required, "要介護度", class: "care-recipient-label" %>
      <%= f.select :degree_care_required, [[1],[2],[3],[4],[5]], {}, class: "degree_care_required" %>
      <%= f.label :dementia, "認知症", class: "care-recipient-label" %>
      <%= f.select :dementia, [["有り", 1],["無し", 2]], {}, class: "dementia" %>
    </div>
    <div class="care-recipient-block2">
      <%= f.label :notes, "特記事項", class: "care-recipient-label" %>
      <%= f.text_area :notes, class: "notes" %>
    </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "作成する", class: "care-diary-btn" %>
  <% end %>
</div>

app/views/care_recipients/search.html.erb
<div class="page-title">
  <p>検索結果一覧</p>
</div>
<div class="care-recipient-search">
  <%= form_with url: search_care_recipients_path, method: :get, local: true do |f| %>
    <%= f.text_field :name, class: "form" %>
    <%= f.submit "検索する", class: "btn" %>
  <% end %>
</div>
<%= render 'care_recipients/care_recipients' %>

app/views/care_recipients/show.html.erb
<div class="page-title">
  <p>個別情報</p>
</div>
<div class="care-recipient-contents">
  <%= link_to "/@care_recipients/#{@care_recipient.id}", method: :delete, data: {confirm: "削除しますか？"}  do %>
    <i class="fas fa-trash-alt"></i>
  <% end %>
  <%= link_to edit_care_recipient_path(@care_recipient), class: "care-recipient-edit-btn" do %>
    <i class="fas fa-edit"></i>
  <% end %>
</div>
<div class="care-recipient-show-block1">
  <div class="care-recipient-show-block2">
    <p>名前：<%= @care_recipient.name %></p>
    <p>性別：<%= @care_recipient.sex %></p>
  </div>
  <div class="care-recipient-show-block2">
    <p>生年月日：<%= @care_recipient.birthday.strftime("%Y年%m月%d日") %></p>
    <p>年齢：<%= @care_recipient.age %>歳</p>
  </div>
  <div class="care-recipient-show-block2">
    <p>担当事業所：<%= @care_recipient.facility_in_charge %></p>
    <p>担当ケアマネージャー：<%= @care_recipient.manager_in_charge %></p>
  </div>
  <div class="care-recipient-show-block2">
    <p>要介護度：<%= @care_recipient.degree_care_required %></p>
    <p>認知症：<%= @care_recipient.dementia %></p>
  </div>
  <div class="care-recipient-show-block3">
    <p class="notes">特記事項：<br><%= safe_join(@care_recipient.notes.split("\n"),tag(:br)) %></p>
  </div>
</div>