config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, :only => [:show] do
    get :search, on: :collection
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :posts, :only => [:show, :new, :create, :edit, :update, :destroy] do
    get :search, on: :collection
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end

  resources :care_recipients, :only => [:index, :show, :new, :create, :edit, :update] do
    get :search, on: :collection
  end

  resources :comments, :only => [:new, :create, :destroy]
  resources :tops, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:index, :new, :create, :show]
  resources :care_diaries, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :care_recipients, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care_diary.rb
class CareDiary < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { in: 1..10 }
  validates :date, presence: true
  validates :temperature, presence: true
  validates :breakfast_meal_intake, presence: true, numericality: { only_integer: true, less_than:11}
  validates :lunch_meal_intake, presence: true, numericality: { only_integer: true, less_than:11}
  validates :dinner_meal_intake, presence: true, numericality: { only_integer: true, less_than:11}
  validates :notes, presence: true,  length: { in: 1..255 }
  validates :user_id, presence: true
end

app/models/care_recipient.rb
class CareRecipient < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { in: 1..10 }
  validates :sex, presence: true
  validates :birthday, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
  validates :facility_in_charge, length: { in: 1..50 }, allow_blank: true
  validates :manager_in_charge, length: { in: 1..10 }, allow_blank: true
  validates :degree_care_required, presence: true, numericality: { only_integer: true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5 }
  validates :dementia, presence: true
  validates :notes, length: { in: 1..255 }

  enum sex: { 男: 1, 女: 2 }
  enum dementia: { 有り: 1, 無し: 2 }


end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { in: 1..255 }

  belongs_to :user
  belongs_to :post
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  validates_uniqueness_of :post_id, scope: :user_id

  belongs_to :post
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length: { in: 1..1000 }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true,  length: { in: 1..500 }

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy
  has_many :comment_posts, through: :comments, source: :user

  has_one_attached :img

  def img_resize
    return self.img.variant(combine_options:{gravity: :center, resize:"468x350^", crop:"468x350+0+0"}).processed
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'

  validates :following_id, presence: true
  validates :follower_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, length: { in: 0..10 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }, length: { in: 1..50 }
  validates :password, presence: true, on: :create, length: { in: 5..10 }
  validates :name, presence: true, length: { in: 1..10 }
  validates :company, length: { in: 0..10 }, allow_blank: true
  validates :role, presence: true, numericality: { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 3 }
  validates :text, length: { in: 0..500 }, allow_blank: true

  has_many :messages, dependent: :destroy

  has_many :entries, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  has_many :care_diaries, dependent: :destroy

  has_many :care_recipients, dependent: :destroy

  has_many :posts, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :comment, dependent: :destroy

  has_one_attached :avatar

  def avatar_resize
    return self.avatar.variant(combine_options:{gravity: :center, resize:"190x190^", crop:"190x190+0+0"}).processed
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def liked_by?(post)
    self.likes.exists?(post_id: post.id)
  end

  def update_with_password(params)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params)
    clean_up_passwords
    result
  end

  def self.guest(role)
    find_or_create_by!(name: 'ゲストユーザ', email: SecureRandom.urlsafe_base64(5) + '@example.com', role: role) do |user|
      user.password = SecureRandom.urlsafe_base64(7)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @entries = current_user.entries
  end

  def show
    @room = Room.find(params[:id])
    @entries = @room.entries
    @message = Message.new
    @messages = @room.messages
  end

  def new
    @matchers = current_user.followers & current_user.followings
    @room = Room.new
    @entry = Entry.new
  end

  def create
    room = Room.create(room_params)
    Entry.create(user_id: current_user.id, room_id: room.id)
    entry_params[:entries][:user_ids].each do |id|
      entry = Entry.new
      entry.room_id = room.id
      entry.user_id = id
      entry.save
    end
    redirect_to "/rooms/#{room.id}"
  end

  def destroy


  end

  def room_params
    params.require(:room).permit(:name)
  end

  def entry_params
    params.require(:room).permit(entries: [user_ids: []])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).order(id: "DESC").per(10)

    return unless request.xhr?
    case params[:type]
    when 'posts', 'post', 'user'
      render "tops/#{params[:type]}"
    end
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/care_diarys_helper.rb
module CareDiarysHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/index.html.erb
<div class="page-title">
  <p>メッセージルーム一覧</p>
</div>
<div class="room-index-block">
  <% if current_user.entries.present? %>
    <ul>
      <p class="link"><%= link_to "新たにチャットルームを作成する", new_room_path %></p>

      <% @entries.each do |entry| %>
        <%= link_to room_path(entry.room_id) do %>
          <% if entry.room.name.present? %>
            <li><%= entry.room.name %></li>
          <% else %>
            <li>
              <% entry.room.entries.each do |room_entry| %>
                <%= room_entry.user.name %>,
              <% end %>
              のルーム
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <p>まだ誰ともチャットを始めていないようです。<br>
      まずはチャットルームを作ってみましょう。</p>
      <p class="link"><%= link_to "新たにチャットルームを作成する", new_room_path %></p>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="page-title">
  <p>チャットルームの作成</p>
</div>
<div class="room-new-block">
  <%= form_for @room do |room| %>
    <div class="room-name">
      <p><%= room.label :name, "ルームネーム" %></p>
      <%= room.text_field :name %>
    </div>
    <%= room.fields_for :entries do |e| %>
      <%= e.collection_check_boxes(:user_ids, @matchers, :id, :name) do |user| %>
        <div>
          <%= user.label do %>
            <%= user.check_box %>
            <% if user.object.avatar.attached? %>
              <%= image_tag(user.object.avatar_resize, class: "small-avatar") %>
            <% else %>
              <i class="fas fa-user-circle small-avatar-none avatar"></i>
            <% end %>
            <p><%= user.object.name %></p>
            <p><%= user.object.company %></p>
          <% end %>
        </div>
      <% end %>
      <%= room.submit "作成する" %>
    <% end %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div id="scroll">
  <div class="message-header">
    <p class="title">参加ユーザー</p>
    <% @entries.each do |entry| %>
      <div>
        <%= link_to user_path(entry.user) do %>
          <% if entry.user.avatar.attached? %>
            <%= image_tag(entry.user.avatar_resize, class: "minimum-avatar") %>
          <% else %>
            <i class="fas fa-user-circle minimum-avatar-none"></i>
          <% end %>
          <p class="name"><%= entry.user.name %></p>
          <p class="company"><%= entry.user.company %></p>
        <% end %>
      </div>
    <% end %>
  </div>
  <div id="message-contents">
    <%= render 'messages/messages' %>
  </div>
  <div class="message-form-block">
    <div>
      <%= form_for @message, remote: true do |f| %>
        <%= f.text_area :content %>
        <%= f.hidden_field :room_id, :value => @room.id %>
        <%= f.button style: 'border-style: none;' do %>
          <i class="fas fa-paper-plane"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>