config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, :only => [:show] do
    get :search, on: :collection
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :posts, :only => [:show, :new, :create, :edit, :update, :destroy] do
    get :search, on: :collection
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end

  resources :care_recipients, :only => [:index, :show, :new, :create, :edit, :update] do
    get :search, on: :collection
  end

  resources :comments, :only => [:new, :create, :destroy]
  resources :tops, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:index, :new, :create, :show]
  resources :care_diaries, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :care_recipients, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true,  length: { in: 1..500 }

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy
  has_many :comment_posts, through: :comments, source: :user

  has_one_attached :img

  def img_resize
    return self.img.variant(combine_options:{gravity: :center, resize:"468x350^", crop:"468x350+0+0"}).processed
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to "/posts/#{@post.id}"
    else
      redirect_to "/posts/new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to "/posts/#{params[:id]}"
    else
      redirect_to "/posts/#{params[:id]}/edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    if current_user == post.user
      post.destroy
      redirect_to "/"
    end
  end

  def search
    if params[:content].present?
      @posts = Post.where('content LIKE ?', "%#{params[:content]}%")
      @posts = @posts.page(params[:page]).order(id: "DESC").per(10)
    else
      @posts = Post.none
    end
  end

  def post_params
    params.require(:post).permit(:content, :user_id, :img)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts.html.erb
<div class="scroll-list jscroll">
  <% @posts.each do |post| %>
    <div class="post-block">
      <% if post.user == current_user %>
        <span>
          <%= link_to "/posts/#{post.id}", class: "post-destroy-btn", method: :delete, data: {confirm: "削除しますか？"} do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
          <%= link_to edit_post_path(post), class: "post-edit-btn" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </span>
      <% end %>
      <% if post.img.attached? %>
        <div class="post-img">
          <%= image_tag(post.img_resize) %>
        </div>
      <% end %>
      <%= link_to user_path(post.user.id) do %>
        <% if post.user.avatar.attached? %>
          <%= image_tag(post.user.avatar_resize, class: "small-avatar avatar") %>
        <% else %>
          <i class="fas fa-user-circle small-avatar-none avatar"></i>
        <% end %>
      <% end %>
      <%= link_to post_path(post.id), id: "post-link" do %>
        <div class="link-block">
        </div>
      <% end %>
      <div>
        <div class="name">

        <%= link_to user_path(post.user.id) do %>
            <p><%= post.user.name %></p>
            <p><%= post.user.company %></p>
        <% end %>
      </div>

        <p><%=safe_join(post.content.split("\n"),tag(:br))%></p>
      </div>
      <div id="like-button-<%= post.id %>" class="like-button">
        <%= render partial: 'likes/like', locals: { post: post } %>
      </div>
    </div>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/posts/_search.html.erb
<div class="search">
  <%= form_with url: search_posts_path, method: :get, local: true do |f| %>
    <div>
      <%= f.text_field :content %>
      <%= f.submit "検索する", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="page-title">
  <p>投稿編集</p>
</div>
<div class="post-new-block">
  <%= form_for @post do |f| %>
    <%= f.label :img, class: "file-form" do %>
      <div id="img_preview">
        <% if @post.img.attached? %>
          <%= image_tag(@post.img_resize) %>
        <% else %>
          <i class="fas fa-image"></i>
        <% end %>
      </div>
      <%= f.file_field :img, style: 'display:none' %>
    <% end %>
    <%= f.text_area :content %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "作成する" %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="page-title">
  <p>投稿作成</p>
</div>
<div class="post-new-block">
  <%= form_for @post do |f| %>
    <%= f.label :img, class: "file-form" do %>
      <div id="img_preview">
        <i class="fas fa-image"></i>
      </div>
      <%= f.file_field :img, style: 'display:none' %>
    <% end %>
    <%= f.text_area :content %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "作成する" %>
  <% end %>
</div>

app/views/posts/search.html.erb
<div class="page-title">
  <p>検索結果</p>
</div>
<div class="search">
  <%= form_with url: search_posts_path, method: :get, local: true do |f| %>
    <div>
      <%= f.text_field :content %>
      <%= f.submit "検索する", class: "btn" %>
    </div>
  <% end %>
</div>
<%= render 'posts/posts' %>

app/views/posts/show.html.erb
<div class="post-show-block">
  <div class="post-block">
    <%= link_to user_path(@post.user.id) do %>
      <% if @post.img.attached? %>
        <div class="post-img">
          <%= image_tag(@post.img_resize) %>
        </div>
      <% end %>
      <% if @post.user.avatar.attached? %>
        <%= image_tag(@post.user.avatar_resize, class: "small-avatar avatar") %>
      <% else %>
        <i class="fas fa-user-circle small-avatar-none avatar"></i>
      <% end %>
    <% end %>
    <div>
      <%= link_to user_path(@post.user.id) do %>
        <p class="name"><%= @post.user.name %></p>
      <% end %>
      <p><%=safe_join(@post.content.split("\n"),tag(:br))%></p>
    </div>
    <div id="like-button-<%= @post.id %>" class="like-button">
      <%= render partial: 'likes/like', locals: { post: @post } %>
    </div>
  </div>
</div>
<% if user_signed_in? %>
  <div class="comment-form">
    <%= form_for(@comment, remote: true) do |f| %>
      <div class="">
        <%= f.text_area :content %>
      </div>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :post_id, :value => @post.id %>
        <%= f.button :type => "submit", style: 'border-style: none;' do %>
          <i class="fas fa-paper-plane"></i>
        <% end %>
    <% end %>
  </div>
<% end %>
<div id="comment-inde">
  <%= render partial: 'comments/index', locals: { commets: @commnets } %>
</div>